logger:
  level: debug

global:
  max:
    ue: 1024

smf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777

  pfcp:
    server:
      - address: 0.0.0.0
        advertise: smf
    client:
      upf:
        - address: 172.18.0.2

  gtpc:
    server:
      - address: 0.0.0.0

  gtpu:
    server:
      - address: 0.0.0.0

  metrics:
    server:
      - address: 0.0.0.0
        port: 9090

  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1

  dns:
    - 8.8.8.8
    - 8.8.4.4

  mtu: 1400

  freeDiameter: /usr/local/etc/freeDiameter/smf.conf